### ISSUE TITLE
Error on disconnecting Websockets

### ISSUE THREAD

**Issue by timeyyy** [benjaoming/django-nyt#38]
Latest pre release `1.0b5`
Using sockets, when i navigate away from a page.

```17-06-24 10:10:15,607 DEBUG Removing connection for user AnonymousUser (disconnect)
2017-06-24 10:10:15,607 - ERROR - worker - Error processing message with consumer django_nyt.consumers.ws
_disconnect:
Traceback (most recent call last):
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/channels/worker.py", line 119, i
n run
    consumer(message, **kwargs)
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/channels/sessions.py", line 78,
in inner
    return func(*args, **kwargs)
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/channels/auth.py", line 42, in i
nner
    return func(message, *args, **kwargs)
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/django_nyt/consumers.py", line 3
8, in ws_disconnect
    for subscription in models.Subscription.objects.filter(settings__user=message.user):
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/django/db/models/manager.py", li
ne 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/django/db/models/query.py", line
 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/django/db/models/query.py", line
 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/django/db/models/sql/query.py",
line 1261, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/django/db/models/sql/query.py",
line 1287, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/django/db/models/sql/query.py",
line 1217, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/django/db/models/lookups.py", li
ne 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/django/db/models/fields/related_
lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/tim/.virtualenvs/poolbook3.6.1/lib/python3.6/site-packages/django/db/models/fields/__init__
.py", line 966, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'AnonymousUser'```

**Comment by timeyyy** [comment]
it was my error
